import os
# import json

import crud
import model
import server

with server.app.app_context():

    os.system("dropdb seed")
    os.system("createdb seed")

    model.connect_to_db(server.app)
    model.db.create_all()

    # Test seed
    user1 = model.User(email="test@test.com", username="user1", password="password2")
    model.db.session.add(user1)

    user2 = model.User(email="juliette@juliette.com", username="juliette", password="juliette")
    model.db.session.add(user2)

    restaurant1 = model.Restaurant(name="Starbucks", address="123 Street Road")
    model.db.session.add(restaurant1)

    achievement1 = model.Achievement(name="Restaurant Explorer 1", description="Visited your first restaurant", points=5)
    model.db.session.add(achievement1)
    achievement2 = model.Achievement(name="Restaurant Explorer 2", description="Visited five restaurants", points=10)
    model.db.session.add(achievement2)
    achievement3 = model.Achievement(name="List Maker 1", description="Created your first list", points=5)
    model.db.session.add(achievement3)
    achievement4 = model.Achievement(name="Dreamer 1", description="Added a restaurant to a list", points=5)
    model.db.session.add(achievement4)
    achievement5 = model.Achievement(name="Tagger 1", description="Assigned your first tag", points=5)
    model.db.session.add(achievement5)
    achievement6 = model.Achievement(name="Tagger 2", description="Assigned a tag to a restaurant five times", points=10)
    model.db.session.add(achievement6)

    tag1 = model.Tag(name="Vegetarian")
    model.db.session.add(tag1)
    tag2 = model.Tag(name="Vegan")
    model.db.session.add(tag2)
    tag3 = model.Tag(name="Gluten-free")
    model.db.session.add(tag3)
    tag4 = model.Tag(name="Halal")
    model.db.session.add(tag4)
    tag5 = model.Tag(name="Kosher")
    model.db.session.add(tag5)
    tag6 = model.Tag(name="Family-friendly")
    model.db.session.add(tag6)
    tag7 = model.Tag(name="Cheap Eats")
    model.db.session.add(tag7)
    tag8 = model.Tag(name="Woman-owned")
    model.db.session.add(tag8)
    tag9 = model.Tag(name="Black-owned")
    model.db.session.add(tag9)
    tag10 = model.Tag(name="Dog-friendly")
    model.db.session.add(tag10)

    user1.achievements.append(achievement1)

    list1 = model.Wishlist(user_id=1, name="Wishlist", description="user1's wishlist")
    model.db.session.add(list1)

    model.db.session.commit()

    listitem = model.ListItem(list_id=1, user_id=1, restaurant_id=1)
    model.db.session.add(listitem)
    model.db.session.commit()

    restaurant2 = model.Restaurant(name="Food", address="Food store")
    model.db.session.add(restaurant2)
    model.db.session.commit()

    listitem2 = model.ListItem(list_id=1, user_id=1, restaurant_id=2)
    model.db.session.add(listitem2)
    model.db.session.commit()

    usertag = model.UserTag(user_id=1, tag_id=1, restaurant_id=2)
    model.db.session.add(usertag)
    model.db.session.commit()

    user1.visits.append(restaurant1)

    users_dict = []
    users_dict.append({'username': 'moodyfoodie', 'email': 'mf@email.com', 'password': 'password'})
    users_dict.append({'username': 'the_yolker', 'email': 'ty@email.com', 'password': 'password'})
    users_dict.append({'username': 'juliab94', 'email': 'jb94@email.com', 'password': 'password'})
    users_dict.append({'username': 'fivebelowzer0', 'email': 'fbz@email.com', 'password': 'password'})
    users_dict.append({'username': 'florida_man', 'email': 'fm@email.com', 'password': 'password'})
    users_dict.append({'username': 'DonkeyDoug', 'email': 'dd@email.com', 'password': 'password'})
    users_dict.append({'username': 'ketchupmustard', 'email': 'km@email.com', 'password': 'password'})
    users_dict.append({'username': 'KimGordon1953', 'email': 'kg@email.com', 'password': 'password'})
    users_dict.append({'username': 'number1d1va', 'email': 'n1d@email.com', 'password': 'password'})
    users_dict.append({'username': 'infinite_pastabilities', 'email': 'ip@email.com', 'password': 'password'})
    users_dict.append({'username': 'foodhater', 'email': 'fh@email.com', 'password': 'password'})
    users_dict.append({'username': 'la_gourmande', 'email': 'lg@email.com', 'password': 'password'})
    users_dict.append({'username': 'mikkomarshmallow', 'email': 'meeks@email.com', 'password': 'password'})

    for account in users_dict:
        new_user = crud.create_user(email=account['email'], username=account['username'], password=account['password'])
        model.db.session.add(new_user)
    model.db.session.commit()

    moodyfoodie = crud.get_user_by_username('moodyfoodie')
    the_yolker = crud.get_user_by_username('the_yolker')
    juliab94 = crud.get_user_by_username('juliab94')
    fivebelowzer0 = crud.get_user_by_username('fivebelowzer0')
    florida_man = crud.get_user_by_username('florida_man')
    DonkeyDoug = crud.get_user_by_username('DonkeyDoug')
    ketchupmustard = crud.get_user_by_username('ketchupmustard')
    KimGordon1953 = crud.get_user_by_username('KimGordon1953')
    number1d1va = crud.get_user_by_username('number1d1va')
    infinite_pastabilities = crud.get_user_by_username('infinite_pastabilities')
    foodhater = crud.get_user_by_username('foodhater')
    la_gourmande = crud.get_user_by_username('la_gourmande')
    mikkomarshmallow = crud.get_user_by_username('mikkomarshmallow')

    badge1 = crud.get_achievement_by_name('Restaurant Explorer 1')
    badge2 = crud.get_achievement_by_name('Restaurant Explorer 2')
    badge3 = crud.get_achievement_by_name('List Maker 1')
    badge4 = crud.get_achievement_by_name('Dreamer 1')
    badge5 = crud.get_achievement_by_name('Tagger 1')
    badge6 = crud.get_achievement_by_name('Tagger 2')
    
    crud.add_achievement(moodyfoodie, badge1)
    crud.add_achievement(moodyfoodie, badge2)
    crud.add_achievement(moodyfoodie, badge3)
    crud.add_achievement(moodyfoodie, badge4)
    crud.add_achievement(moodyfoodie, badge5)
    crud.add_achievement(the_yolker, badge1)
    crud.add_achievement(the_yolker, badge2)
    crud.add_achievement(the_yolker, badge3)
    crud.add_achievement(the_yolker, badge4)
    crud.add_achievement(the_yolker, badge5)
    crud.add_achievement(the_yolker, badge6)
    crud.add_achievement(juliab94, badge1)
    crud.add_achievement(fivebelowzer0, badge1)
    crud.add_achievement(fivebelowzer0, badge2)
    crud.add_achievement(fivebelowzer0, badge3)
    crud.add_achievement(florida_man, badge1)
    crud.add_achievement(florida_man, badge2)
    crud.add_achievement(florida_man, badge3)
    crud.add_achievement(florida_man, badge4)
    crud.add_achievement(DonkeyDoug, badge1)
    crud.add_achievement(DonkeyDoug, badge2)
    crud.add_achievement(DonkeyDoug, badge3)
    crud.add_achievement(DonkeyDoug, badge4)
    crud.add_achievement(ketchupmustard, badge1)
    crud.add_achievement(ketchupmustard, badge2)
    crud.add_achievement(KimGordon1953, badge1)
    crud.add_achievement(number1d1va, badge1)
    crud.add_achievement(number1d1va, badge2)
    crud.add_achievement(number1d1va, badge3)
    crud.add_achievement(infinite_pastabilities, badge1)
    crud.add_achievement(infinite_pastabilities, badge2)
    crud.add_achievement(infinite_pastabilities, badge3)
    crud.add_achievement(infinite_pastabilities, badge4)
    crud.add_achievement(la_gourmande, badge1)
    crud.add_achievement(la_gourmande, badge2)
    crud.add_achievement(mikkomarshmallow, badge1)
    crud.add_achievement(mikkomarshmallow, badge2)
    model.db.session.commit()
